version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "first-sam-app-2nd-actually"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1w94vblw6vtzq"
s3_prefix = "first-sam-app-2nd-actually"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
